//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\Vaishnavi\Solution_AutoHoleInspector\HoleSelectionUI.cs
//
//        This file was generated by the NX Block UI Styler
//        Created by: HP
//              Version: NX 2306
//              Date: 12-29-2025  (Format: mm-dd-yyyy)
//              Time: 13:48 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C# source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These imports are needed for the following template code
//------------------------------------------------------------------------------
using NXOpen;
using NXOpen.BlockStyler;
using NXOpen.UF;
using NXOpen.VectorArithmetic;
using System;


//------------------------------------------------------------------------------
//Represents Block Styler application class
//------------------------------------------------------------------------------
public class HoleSelectionUI
{
    //class members
    private static Session theSession = null;
    private static UI theUI = null;
    private string theDlxFileName;
    private NXOpen.BlockStyler.BlockDialog theDialog;
    private NXOpen.BlockStyler.Group group0;
    private NXOpen.BlockStyler.SelectObject holeOneID;
    private NXOpen.BlockStyler.SelectObject holeTwoID;
    private static UFSession theUfSession = UFSession.GetUFSession();

    // Block type: Selection
    private NXOpen.BlockStyler.SpecifyCSYS csysID;// Block type: Specify Csys
    //------------------------------------------------------------------------------
    //Bit Option for Property: SnapPointTypesEnabled
    //------------------------------------------------------------------------------
    public static readonly int SnapPointTypesEnabled_UserDefined = (1 << 0);
    public static readonly int SnapPointTypesEnabled_Inferred = (1 << 1);
    public static readonly int SnapPointTypesEnabled_ScreenPosition = (1 << 2);
    public static readonly int SnapPointTypesEnabled_EndPoint = (1 << 3);
    public static readonly int SnapPointTypesEnabled_MidPoint = (1 << 4);
    public static readonly int SnapPointTypesEnabled_ControlPoint = (1 << 5);
    public static readonly int SnapPointTypesEnabled_Intersection = (1 << 6);
    public static readonly int SnapPointTypesEnabled_ArcCenter = (1 << 7);
    public static readonly int SnapPointTypesEnabled_QuadrantPoint = (1 << 8);
    public static readonly int SnapPointTypesEnabled_ExistingPoint = (1 << 9);
    public static readonly int SnapPointTypesEnabled_PointonCurve = (1 << 10);
    public static readonly int SnapPointTypesEnabled_PointonSurface = (1 << 11);
    public static readonly int SnapPointTypesEnabled_PointConstructor = (1 << 12);
    public static readonly int SnapPointTypesEnabled_TwocurveIntersection = (1 << 13);
    public static readonly int SnapPointTypesEnabled_TangentPoint = (1 << 14);
    public static readonly int SnapPointTypesEnabled_Poles = (1 << 15);
    public static readonly int SnapPointTypesEnabled_BoundedGridPoint = (1 << 16);
    public static readonly int SnapPointTypesEnabled_FacetVertexPoint = (1 << 17);
    public static readonly int SnapPointTypesEnabled_DefiningPoint = (1 << 18);
    //------------------------------------------------------------------------------
    //Bit Option for Property: SnapPointTypesOnByDefault
    //------------------------------------------------------------------------------
    public static readonly int SnapPointTypesOnByDefault_EndPoint = (1 << 3);
    public static readonly int SnapPointTypesOnByDefault_MidPoint = (1 << 4);
    public static readonly int SnapPointTypesOnByDefault_ControlPoint = (1 << 5);
    public static readonly int SnapPointTypesOnByDefault_Intersection = (1 << 6);
    public static readonly int SnapPointTypesOnByDefault_ArcCenter = (1 << 7);
    public static readonly int SnapPointTypesOnByDefault_QuadrantPoint = (1 << 8);
    public static readonly int SnapPointTypesOnByDefault_ExistingPoint = (1 << 9);
    public static readonly int SnapPointTypesOnByDefault_PointonCurve = (1 << 10);
    public static readonly int SnapPointTypesOnByDefault_PointonSurface = (1 << 11);
    public static readonly int SnapPointTypesOnByDefault_PointConstructor = (1 << 12);
    public static readonly int SnapPointTypesOnByDefault_BoundedGridPoint = (1 << 16);
    public static readonly int SnapPointTypesOnByDefault_FacetVertexPoint = (1 << 17);

    //------------------------------------------------------------------------------
    //Constructor for NX Styler class
    //------------------------------------------------------------------------------
    public HoleSelectionUI()
    {
        try
        {
            theSession = Session.GetSession();
            theUI = UI.GetUI();
            theDlxFileName = "HoleSelectionUI.dlx";
            theDialog = theUI.CreateDialog(System.IO.Path.Combine(AppContext.BaseDirectory, theDlxFileName));
            theDialog.AddApplyHandler(new NXOpen.BlockStyler.BlockDialog.Apply(apply_cb));
            theDialog.AddOkHandler(new NXOpen.BlockStyler.BlockDialog.Ok(ok_cb));
            theDialog.AddUpdateHandler(new NXOpen.BlockStyler.BlockDialog.Update(update_cb));
            theDialog.AddInitializeHandler(new NXOpen.BlockStyler.BlockDialog.Initialize(initialize_cb));
            theDialog.AddDialogShownHandler(new NXOpen.BlockStyler.BlockDialog.DialogShown(dialogShown_cb));
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            throw ex;
        }
    }
    //------------------------------- DIALOG LAUNCHING ---------------------------------
    //
    //    Before invoking this application one needs to open any part/empty part in NX
    //    because of the behavior of the blocks.
    //
    //    Make sure the dlx file is in one of the following locations:
    //        1.) From where NX session is launched
    //        2.) $UGII_USER_DIR/application
    //        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
    //            recommended. This variable is set to a full directory path to a file 
    //            containing a list of root directories for all custom applications.
    //            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
    //
    //    You can create the dialog using one of the following way:
    //
    //    1. Journal Replay
    //
    //        1) Replay this file through Tool->Journal->Play Menu.
    //
    //    2. USER EXIT
    //
    //        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
    //        2) Invoke the Shared Library through File->Execute->NX Open menu.
    //
    //------------------------------------------------------------------------------
    public static void Main()
    {
        HoleSelectionUI theHoleSelectionUI = null;
        try
        {
            theHoleSelectionUI = new HoleSelectionUI();
            // The following method shows the dialog immediately
            theHoleSelectionUI.Launch();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        finally
        {
            if (theHoleSelectionUI != null)
                theHoleSelectionUI.Dispose();
            theHoleSelectionUI = null;
        }
    }
    //------------------------------------------------------------------------------
    // This method specifies how a shared image is unloaded from memory
    // within NX. This method gives you the capability to unload an
    // internal NX Open application or user  exit from NX. Specify any
    // one of the three constants as a return value to determine the type
    // of unload to perform:
    //
    //
    //    Immediately : unload the library as soon as the automation program has completed
    //    Explicitly  : unload the library from the "Unload Shared Image" dialog
    //    AtTermination : unload the library when the NX session terminates
    //
    //
    // NOTE:  A program which associates NX Open applications with the menubar
    // MUST NOT use this option since it will UNLOAD your NX Open application image
    // from the menubar.
    //------------------------------------------------------------------------------
    public static int GetUnloadOption(string arg)
    {
        //return System.Convert.ToInt32(Session.LibraryUnloadOption.Explicitly);
        return System.Convert.ToInt32(Session.LibraryUnloadOption.Immediately);
        // return System.Convert.ToInt32(Session.LibraryUnloadOption.AtTermination);
    }

    //------------------------------------------------------------------------------
    // Following method cleanup any housekeeping chores that may be needed.
    // This method is automatically called by NX.
    //------------------------------------------------------------------------------
    public static void UnloadLibrary(string arg)
    {
        try
        {
            //---- Enter your code here -----
            GetUnloadOption(arg);
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }

    //------------------------------------------------------------------------------
    //This method launches the dialog to screen
    //------------------------------------------------------------------------------
    public NXOpen.BlockStyler.BlockDialog.DialogResponse Launch()
    {
        NXOpen.BlockStyler.BlockDialog.DialogResponse dialogResponse = NXOpen.BlockStyler.BlockDialog.DialogResponse.Invalid;
        try
        {
            dialogResponse = theDialog.Launch();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return dialogResponse;
    }

    //------------------------------------------------------------------------------
    //Method Name: Dispose
    //------------------------------------------------------------------------------
    public void Dispose()
    {
        if (theDialog != null)
        {
            theDialog.Dispose();
            theDialog = null;
        }
    }

    //------------------------------------------------------------------------------
    //---------------------Block UI Styler Callback Functions--------------------------
    //------------------------------------------------------------------------------

    //------------------------------------------------------------------------------
    //Callback Name: initialize_cb
    //------------------------------------------------------------------------------
    public void initialize_cb()
    {
        try
        {
            group0 = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group0");
            holeOneID = (NXOpen.BlockStyler.SelectObject)theDialog.TopBlock.FindBlock("holeOneID");
            holeTwoID = (NXOpen.BlockStyler.SelectObject)theDialog.TopBlock.FindBlock("holeTwoID");

            csysID = (SpecifyCSYS)theDialog.TopBlock.FindBlock("csysID");

            // ===============================
            // FILTER FOR DATUM HOLE 1
            // ===============================
            holeOneID.ClearFilter();

            NXOpen.Selection.MaskTriple circularEdgeMask =
                new NXOpen.Selection.MaskTriple(
                    UFConstants.UF_solid_type,
                    0,
                    UFConstants.UF_UI_SEL_FEATURE_CIRCULAR_EDGE
                );

            holeOneID.SetSelectionFilter(
                NXOpen.Selection.SelectionAction.ClearAndEnableSpecific,
                new NXOpen.Selection.MaskTriple[] { circularEdgeMask }
            );

            holeOneID.MaximumScopeAsString = "Entire Assembly";

            // ===============================
            // FILTER FOR DATUM HOLE 2
            // ===============================
            holeTwoID.ClearFilter();

            holeTwoID.SetSelectionFilter(
                NXOpen.Selection.SelectionAction.ClearAndEnableSpecific,
                new NXOpen.Selection.MaskTriple[] { circularEdgeMask }
            );

            holeTwoID.MaximumScopeAsString = "Entire Assembly";
        }
        catch (Exception ex)
        {
            theUI.NXMessageBox.Show(
                "Block Styler",
                NXMessageBox.DialogType.Error,
                ex.ToString()
            );
        }
    }


    //------------------------------------------------------------------------------
    //Callback Name: dialogShown_cb
    //This callback is executed just before the dialog launch. Thus any value set 
    //here will take precedence and dialog will be launched showing that value. 
    //------------------------------------------------------------------------------
    public void dialogShown_cb()
    {
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }

    //------------------------------------------------------------------------------
    //Callback Name: apply_cb
    //------------------------------------------------------------------------------
    public int apply_cb()
    {
        int errorCode = 0;
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            errorCode = 1;
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return errorCode;
    }

    //------------------------------------------------------------------------------
    //Callback Name: update_cb
    //------------------------------------------------------------------------------
    public int update_cb(NXOpen.BlockStyler.UIBlock block)
    {
        try
        {
            if (block == holeOneID)
            {
                //---------Enter your code here-----------
            }
            else if (block == holeTwoID)
            {
                //---------Enter your code here-----------
            }
            else if (block == csysID)
            {
                //---------Enter your code here-----------
            }
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }

    //------------------------------------------------------------------------------
    //Callback Name: ok_cb
    //------------------------------------------------------------------------------
    public int ok_cb()
    {
        try
        {
            Edge hole1 = GetSelectedHoleEdge(holeOneID, "Datum Hole 1");
            Edge hole2 = GetSelectedHoleEdge(holeTwoID, "Datum Hole 2");

            //--slection of csys
            //PropertyList csysProps = csysID.GetProperties();
            //TaggedObject csysObj = csysProps.GetTaggedObject("SelectedCsys");

            //CoordinateSystem carLineCsys = csysObj as CoordinateSystem;

            //if (carLineCsys == null)
            //    throw new Exception("Please select a valid Datum CSYS.");


            double dia1 = GetDiameterFromCircularEdge(hole1);
            double dia2 = GetDiameterFromCircularEdge(hole2);
            double pitch = GetPitchBetweenHoles(hole1, hole2);
            //Vector3d xyz1 = GetXYZWrtCsys(hole1, carLineCsys);
            //Vector3d xyz2 = GetXYZWrtCsys(hole2, carLineCsys);




            theUI.NXMessageBox.Show(
                "Hole Diameters",
                NXMessageBox.DialogType.Information,
                $"Datum Hole 1 Diameter = {dia1:F3} mm\n" +
                $"Datum Hole 2 Diameter = {dia2:F3} mm\n" +
                $"Pitch Distance = {pitch:F3} mm\n\n"
            //$"Hole 2 XYZ (Car Line) = X:{xyz2.X:F3}, Y:{xyz2.Y:F3}, Z:{xyz2.Z:F3}\n\n" +
            //$"Hole 1 XYZ (Car Line) = X:{xyz1.X:F3}, Y:{xyz1.Y:F3}, Z:{xyz1.Z:F3}\n"
            );
            return 0;
        }
        catch (Exception ex)
        {
            theUI.NXMessageBox.Show(
                "Hole Selection Error",
                NXMessageBox.DialogType.Error,
                ex.Message
            );
            return 1;
        }
    }

    private Edge GetSelectedHoleEdge(NXOpen.BlockStyler.SelectObject holeBlock, string holeName)

    {
        TaggedObject[] selectedObjects = holeBlock.GetSelectedObjects();

        if (selectedObjects == null || selectedObjects.Length == 0)
            throw new Exception($"Please select {holeName}.");

        Edge edge = selectedObjects[0] as Edge;

        if (edge == null)
            throw new Exception($"{holeName} is not a circular edge.");

        return edge;
    }

    //Finding Diameter
    private double GetDiameterFromCircularEdge(Edge edge)
    {
        Part workPart = theSession.Parts.Work;

        Unit mmUnit = workPart.UnitCollection.FindObject("MilliMeter") as Unit;

        NXObject[] sellist = new NXObject[] { edge };

        bool isApproximate;
        double arcLength;
        double radius;
        double diameter;
        double minRadius;
        Point3d startPoint;
        Point3d endPoint;
        Point3d arcCenter;

        theSession.Measurement.GetArcAndCurveProperties(
            sellist,
            mmUnit,
            true,
            out isApproximate,
            out arcLength,
            out radius,
            out diameter,
            out minRadius,
            out startPoint,
            out endPoint,
            out arcCenter
        );

        return diameter;
    }

    //Finding Pitch Distance

    private double GetPitchBetweenHoles(Edge hole1, Edge hole2)
    {
        Part workPart = theSession.Parts.Work;

        Point p1 = workPart.Points.CreatePoint(
            hole1,
            SmartObject.UpdateOption.AfterModeling
        );
        Point p2 = workPart.Points.CreatePoint(
            hole2,
            SmartObject.UpdateOption.AfterModeling
        );

        p1.RemoveViewDependency();
        p2.RemoveViewDependency();

        Point3d c1 = p1.Coordinates;
        Point3d c2 = p2.Coordinates;

        double dx = Math.Abs(c2.X - c1.X);
        double dy = Math.Abs(c2.Y - c1.Y);
        double dz = Math.Abs(c2.Z - c1.Z);

        // 🔹 NX-style automatic vector selection
        double pitch;

        if (dx >= dy && dx >= dz)
            pitch = dx;      // X-dominant
        else if (dy >= dx && dy >= dz)
            pitch = dy;      // Y-dominant 
        else
            pitch = dz;      // Z-dominant

        workPart.Points.DeletePoint(p1);
        workPart.Points.DeletePoint(p2);

        return pitch;
    }


   
    //x,y,z w.r.t car line
    // ===============================
    // X, Y, Z w.r.t. Car Line (CSYS)
    // ===============================
    //    private Vector3d GetXYZWrtCsys(Edge holeEdge, CoordinateSystem csys)
    //    {
    //        Part workPart = theSession.Parts.Work;

    //        // 1. Create hole center point
    //        Point p = workPart.Points.CreatePoint(
    //            holeEdge,
    //            SmartObject.UpdateOption.AfterModeling
    //        );
    //        p.RemoveViewDependency();

    //        Point3d holeAbs = p.Coordinates;

    //        // 2. Ask CSYS origin + orientation using UF (CORRECT way)
    //        double[] csysOrigin = new double[3];
    //        double[] matrix = new double[9];

    //        theUfSession.Csys.AskCsysInfo(
    //    csys.Tag,
    //    out csysOrigin,
    //    out matrix
    //);


    //        // 3. Vector from CSYS origin → hole
    //        Vector3d delta = new Vector3d(
    //            holeAbs.X - csysOrigin[0],
    //            holeAbs.Y - csysOrigin[1],
    //            holeAbs.Z - csysOrigin[2]
    //        );

    //        // 4. Project into CSYS axes
    //        double x = delta.X * matrix[0] + delta.Y * matrix[1] + delta.Z * matrix[2];
    //        double y = delta.X * matrix[3] + delta.Y * matrix[4] + delta.Z * matrix[5];
    //        double z = delta.X * matrix[6] + delta.Y * matrix[7] + delta.Z * matrix[8];

    //        // 5. Cleanup
    //        workPart.Points.DeletePoint(p);

    //        return new Vector3d(x, y, z);
    //    }









     //------------------------------------------------------------------------------
    //Function Name: GetBlockProperties
    //Returns the propertylist of the specified BlockID
    //------------------------------------------------------------------------------
    public PropertyList GetBlockProperties(string blockID)
    {
        PropertyList plist = null;
        try
        {
            plist = theDialog.GetBlockProperties(blockID);
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return plist;
    }




}
